[book]
title = "hello world docs | $NEWS"
description = "Technical documentation for hello world & $NEWS"
authors = ["bfantana"]
language = "en"
multilingual = false
src = "src"

[output.html]
cname = "docs.helloworld.news"
