[book]
title = "helloWorldDocs"
language = "en"
multilingual = false
src = "src"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/helloWorldNft/docs.helloworld.news"
git-repository-icon = "fa-github"